# Generated by Django 5.0.6 on 2024-05-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='owner',
        ),
    ]
