# Generated by Django 5.0.6 on 2024-05-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0005_alter_comments_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(verbose_name='текст комментария'),
        ),
    ]
